const USER_SEARCH_BUTTON = "UserSearchButton";
const SUBMIT_USER_EDIT_BUTTON = "SubmitUserEditButton";
const CANCEL_USER_EDIT_BUTTON = "CancelUserEditButton";
const CANCEL_USER_SEARCH_BUTTON = "CancelUserSearchButton";
const SUBMIT_USER_SEARCH_BUTTON = "SubmitUserSearchButton";
const USER_EDIT_BUTTON = "UserEditButton";

export {
  USER_SEARCH_BUTTON,
  SUBMIT_USER_EDIT_BUTTON,
  CANCEL_USER_EDIT_BUTTON,
  CANCEL_USER_SEARCH_BUTTON,
  SUBMIT_USER_SEARCH_BUTTON,
  USER_EDIT_BUTTON
}