const USER_SEARCH_BUTTON = "UserSearchButton";
const SUBMIT_USER_EDIT_BUTTON = "SubmitUserEditButton";
const CANCEL_USER_EDIT_BUTTON = "CancelUserEditButton";
const CANCEL_USER_SEARCH_BUTTON = "CancelUserSearchButton";
const SUBMIT_USER_SEARCH_BUTTON = "SubmitUserSearchButton";
const USER_EDIT_BUTTON = "UserEditButton";

const CANCEL_PROJECT_SEARCH_BUTTON = "CancelProjectSearchButton";
const SUBMIT_PROJECT_SEARCH_BUTTON = "SubmitProjectSearchButton";
const PROJECT_EDIT_BUTTON = "ProjectEditButton";
const CANCEL_PROJECT_EDIT_BUTTON = "CancelProjectEditButton";
const SUBMIT_PROJECT_EDIT_BUTTON = "SubmitProjectEditButton";
const PROJECT_NEW_BUTTON = "ProjectNewButton";
const CANCEL_PROJECT_NEW_BUTTON = "CancelProjectNewButton";
const SUBMIT_PROJECT_NEW_BUTTON = "SubmitProjectNewButton";

const PROJECT_ACTION_SHEET_BUTTON = "ProjectActionSheetButton";
const BACK_BUTTON = "BackButton";
const SUBMIT_BUTTON = "SubmitButton";
const SEARCH_BUTTON = "SearchButton";
const CANCEL_BUTTON = "CancelButton";

export {
  USER_SEARCH_BUTTON,
  SUBMIT_USER_EDIT_BUTTON,
  CANCEL_USER_EDIT_BUTTON,
  CANCEL_USER_SEARCH_BUTTON,
  SUBMIT_USER_SEARCH_BUTTON,
  USER_EDIT_BUTTON,
  CANCEL_PROJECT_SEARCH_BUTTON,
  SUBMIT_PROJECT_SEARCH_BUTTON,
  PROJECT_EDIT_BUTTON,
  CANCEL_PROJECT_EDIT_BUTTON,
  SUBMIT_PROJECT_EDIT_BUTTON,
  PROJECT_NEW_BUTTON,
  SUBMIT_PROJECT_NEW_BUTTON,
  CANCEL_PROJECT_NEW_BUTTON,
  PROJECT_ACTION_SHEET_BUTTON,
  BACK_BUTTON,
  SUBMIT_BUTTON,
  SEARCH_BUTTON,
  CANCEL_BUTTON
};
