const APP_NAME = "side-project";
const TOP_SCREEN = `${APP_NAME}.TopScreen`;
const USER_DISCOVERY_SCREEN = `${APP_NAME}.UserDisccoveryScreen`;
const USER_DETAILS_SCREEN = `${APP_NAME}.UserDetailsScreen`;

const USER_SEARCH_MODAL_SCREEN = `${APP_NAME}.UserSearchModalScreen`;
const AUTH_SCREEN = `${APP_NAME}.AuthScreen`;
const SKILL_SEARCH_MODAL_SCREEN = `${APP_NAME}.SkillSearchModalScreen`;

const MATCH_SCREEN = `${APP_NAME}.MatchScreen`;
const CHAT_SCREEN = `${APP_NAME}.ChatScreen`;

const USER_EDIT_SCREEN = `${APP_NAME}.UserEditScreen`;

const MY_PROFILE_SCREEN = `${APP_NAME}.MyProfileScreen`;


const PROJECT_DETAILS_SCREEN = `${APP_NAME}.ProjectDetailsScreen`;

const PROJECT_LIST_SCREEN = `${APP_NAME}.ProjectListScreen`;
const PROJECT_EDIT_SCREEN = `${APP_NAME}.ProjectEditScreen`;
const PROJECT_DISCOVERY_SCREEN = `${APP_NAME}.ProjectDiscoveryScreen`;
const PROJECT_SEARCH_MODAL_SCREEN = `${APP_NAME}.ProjectSearchModalScreen`;

const SETTINGS_LIST_SCREEN = `${APP_NAME}.SettingsListScreen`;

export {
  USER_DISCOVERY_SCREEN,
  USER_SEARCH_MODAL_SCREEN,
  SKILL_SEARCH_MODAL_SCREEN,
  TOP_SCREEN,
  AUTH_SCREEN,
  USER_DETAILS_SCREEN,
  
  MATCH_SCREEN,
  CHAT_SCREEN,

  MY_PROFILE_SCREEN,
  USER_EDIT_SCREEN,
  PROJECT_DETAILS_SCREEN,
  PROJECT_EDIT_SCREEN,
  PROJECT_LIST_SCREEN,
  PROJECT_DISCOVERY_SCREEN,
  PROJECT_SEARCH_MODAL_SCREEN,
  SETTINGS_LIST_SCREEN,

};
