const APP_NAME = 'side-project';
const INITIALIZE_SCREEN = `${APP_NAME}.InitializeScreen`;
const TOP_SCREEN = `${APP_NAME}.TopScreen`;
const DISCOVERY_SCREEN = `${APP_NAME}.DisccoveryScreen`;
const USER_DETAILS_SCREEN = `${APP_NAME}.UserDetailsScreen`;

const USER_SEARCH_MODAL_SCREEN = `${APP_NAME}.UserSearchModalScreen`;
const PROJECT_SEARCH_MODAL_SCREEN = `${APP_NAME}.ProjectSearchModalScreen`;
const AUTH_SCREEN = `${APP_NAME}.AuthScreen`;
const MATCH_SCREEN = `${APP_NAME}.MatchScreen`;
const CHAT_SCREEN = `${APP_NAME}.ChatScreen`;

const USER_EDIT_SCREEN = `${APP_NAME}.UserEditScreen`;

const MY_PROFILE_SCREEN = `${APP_NAME}.MyProfileScreen`;

const PROJECT_DETAILS_SCREEN = `${APP_NAME}.ProjectDetailsScreen`;
const LIKED_PROJECT_DETAILS_SCREEN = `${APP_NAME}.LikedProjectDetailsScreen`;
const PROJECT_LIST_SCREEN = `${APP_NAME}.ProjectListScreen`;
const PROJECT_NEW_SCREEN = `${APP_NAME}.ProjectNewScreen`;
const PROJECT_EDIT_SCREEN = `${APP_NAME}.ProjectEditScreen`;
const PROJECT_DISCOVERY_SCREEN = `${APP_NAME}.ProjectDiscoveryScreen`;

const SETTING_LIST_SCREEN = `${APP_NAME}.SettingListScreen`;

const SKILL_SEARCH_MODAL_SCREEN = `${APP_NAME}.SkillSearchModalScreen`;
const CITY_SEARCH_MODAL_SCREEN = `${APP_NAME}.CitySearchModalScreen`;
const SELECT_BOX_PICKER_SCREEN = `${APP_NAME}.SelectBoxPickerScreen`;
const TEXT_INPUT_SCREEN = `${APP_NAME}.TextInputScreen`;
const PHOTOS_EDIT_SCREEN = `${APP_NAME}.PhotosEditScreen`;

export {
  INITIALIZE_SCREEN,
  DISCOVERY_SCREEN,
  USER_SEARCH_MODAL_SCREEN,
  PROJECT_SEARCH_MODAL_SCREEN,
  SKILL_SEARCH_MODAL_SCREEN,
  CITY_SEARCH_MODAL_SCREEN,
  TOP_SCREEN,
  AUTH_SCREEN,
  USER_DETAILS_SCREEN,
  PROJECT_DETAILS_SCREEN,
  MATCH_SCREEN,
  CHAT_SCREEN,
  MY_PROFILE_SCREEN,
  USER_EDIT_SCREEN,
  LIKED_PROJECT_DETAILS_SCREEN,
  PROJECT_EDIT_SCREEN,
  PROJECT_NEW_SCREEN,
  PROJECT_LIST_SCREEN,
  PROJECT_DISCOVERY_SCREEN,
  SETTING_LIST_SCREEN,
  SELECT_BOX_PICKER_SCREEN,
  TEXT_INPUT_SCREEN,
  PHOTOS_EDIT_SCREEN
};
