const APP_NAME = "side-project";
const TOP_SCREEN = `${APP_NAME}.TopScreen`;
const USER_DISCOVERY_SCREEN = `${APP_NAME}.UserDisccoveryScreen`;
const USER_DETAILS_SCREEN = `${APP_NAME}.UserDetailsScreen`;
const PICKER_SCREEN = `${APP_NAME}.PickerScreen`;

const USER_SEARCH_MODAL_SCREEN = `${APP_NAME}.UserSearchModalScreen`;
const PROJECT_SEARCH_MODAL_SCREEN = `${APP_NAME}.ProjectSearchModalScreen`;
const AUTH_SCREEN = `${APP_NAME}.AuthScreen`;
const SKILL_SEARCH_MODAL_SCREEN = `${APP_NAME}.SkillSearchModalScreen`;
const CITY_SEARCH_MODAL_SCREEN = `${APP_NAME}.CitySearchModalScreen`;
const MATCH_SCREEN = `${APP_NAME}.MatchScreen`;
const CHAT_SCREEN = `${APP_NAME}.ChatScreen`;

const USER_EDIT_SCREEN = `${APP_NAME}.UserEditScreen`;

const MY_PROFILE_SCREEN = `${APP_NAME}.MyProfileScreen`;

const PROJECT_DETAILS_SCREEN = `${APP_NAME}.ProjectDetailsScreen`;
const LIKED_PROJECT_DETAILS_SCREEN = `${APP_NAME}.LikedProjectDetailsScreen`;
const PROJECT_LIST_SCREEN = `${APP_NAME}.ProjectListScreen`;
const PROJECT_NEW_SCREEN = `${APP_NAME}.ProjectNewScreen`;
const PROJECT_EDIT_SCREEN = `${APP_NAME}.ProjectEditScreen`;
const PROJECT_DISCOVERY_SCREEN = `${APP_NAME}.ProjectDiscoveryScreen`;

const SETTINGS_LIST_SCREEN = `${APP_NAME}.SettingsListScreen`;

export {
  PICKER_SCREEN,
  USER_DISCOVERY_SCREEN,
  USER_SEARCH_MODAL_SCREEN,
  PROJECT_SEARCH_MODAL_SCREEN,
  SKILL_SEARCH_MODAL_SCREEN,
  CITY_SEARCH_MODAL_SCREEN,
  TOP_SCREEN,
  AUTH_SCREEN,
  USER_DETAILS_SCREEN,
  PROJECT_DETAILS_SCREEN,
  
  MATCH_SCREEN,
  CHAT_SCREEN,

  MY_PROFILE_SCREEN,
  USER_EDIT_SCREEN,
  LIKED_PROJECT_DETAILS_SCREEN,
  PROJECT_EDIT_SCREEN,
  PROJECT_NEW_SCREEN,
  PROJECT_LIST_SCREEN,
  PROJECT_DISCOVERY_SCREEN,
  SETTINGS_LIST_SCREEN,

};
